name: Build vercel preview

run-name: ${{github.repository}} is running

env:
  # Need to add secrets on the Github repository settings page
  # Both ORG_ID and PROJECT_ID are stored in the .vercel/project.json file
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_CODE: ${{ secrets.VITE_CODE }}

on:
  push:
    branches:
      - 'third_action'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Use actions/checkout@v4
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        # Create a Vercel token on the Vercel account settings page
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
